@token = {{Login.response.body.$.accessToken}}

# @name Login
POST http://localhost:3001/auth/login/
content-type: application/json

{
    "username": "admin",
    "password": "IE530C@azf"
}

###
# @name Logout
POST http://localhost:3001/auth/logout/
Authorization: Bearer {{token}}

###
# @name ProtectedRouterTest
GET http://localhost:3001/auth/protected/
Authorization: Bearer {{token}}