services:
  # db:
  #   image: "postgres:16.0-alpine3.18"
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: beachpay
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    expose:
      - "3001"
    env_file:
      - ./apps/api/.env # só para dev
    # depends_on:
    #   db:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: sh -c "pnpm db:deploy && pnpm start"

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    expose:
      - "3000"
    env_file:
      - ./apps/web/.env # só para dev
    command: sh -c "pnpm db:deploy && pnpm start"

volumes:
  pgdata:
