@token = {{Login.response.body.$.accessToken}}
@userId = {{Login.response.body.$.id}}
# @name Login
POST http://localhost:3001/auth/login/
content-type: application/json

{
    "username": "admin",
    "password": "IE530C@azf"
}


###
# @name getUser
GET http://localhost:3001/user/
Authorization: Bearer {{token}}

###
GET http://localhost:3001/user/cm9d2pdws0001owyluixxizeb
Authorization: Bearer {{token}}


### CREATE USER
POST http://localhost:3001/user/
content-type: application/json
Authorization: Bearer {{token}}

{
  "user": "new user",
  "passwd": "securepassword",
  "name": "New User",
  "role": "operational",
  "email": "newuser@example.com"
}


###
DELETE http://localhost:3001/user/cmb6owika0001ow1885vt2got
Authorization: Bearer {{token}}
